[package]
name = "clr1-build"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.1.1", features = ["from"] }
thiserror = "2.0.17"
serde = { version = "1.0.228", features = ["derive"] }
